// DEPLOYMENT GUIDE FOR HTTPS URL
// =====================================
// 1. Copy this project into a React app (Vite or Next.js)
// 2. Push code to GitHub
// 3. Deploy FREE using Vercel or Netlify
// 4. You will get HTTPS URL like:
//    https://ga4-demo.vercel.app
// 5. Paste that URL inside GA4 Data Stream
//
// QUICK VERCEL DEPLOYMENT
// -------------------------------------
// Step 1:
// npm create vite@latest ga4-demo
//
// Step 2:
// Replace App.jsx with this file
//
// Step 3:
// npm install
// npm run dev
//
// Step 4:
// Push to GitHub
//
// Step 5:
// Open https://vercel.com
// Import GitHub repository
// Click Deploy
//
// Step 6:
// Copy HTTPS URL generated by Vercel
// Example:
// https://ga4-learning-demo.vercel.app
//
// Step 7:
// Create GA4 Property
// Admin → Data Streams → Web
// Paste website URL
// Add Measurement ID into gtag code
//
// BONUS:
// You can later connect:
// - Google Tag Manager
// - BigQuery
// - Looker Studio
// - Meta Pixel
// - Hotjar
// =====================================

export default function GA4LearningDemo() {
  const sections = [
    {
      title: "1. Page View Tracking",
      event: "page_view",
      explanation:
        "GA4 automatically tracks when a user visits a page. Every page in your website can generate page_view events.",
      example: "User opens Home Page → GA4 logs page_view",
    },
    {
      title: "2. Button Click Tracking",
      event: "button_click",
      explanation:
        "Custom events help track interactions like CTA clicks, downloads, or signups.",
      example: "User clicks 'Buy Now' button → GA4 logs button_click",
    },
    {
      title: "3. Scroll Tracking",
      event: "scroll",
      explanation:
        "GA4 Enhanced Measurement can automatically track scroll depth.",
      example: "User scrolls 90% of page → GA4 logs scroll",
    },
    {
      title: "4. Video Engagement",
      event: "video_start / video_progress / video_complete",
      explanation:
        "GA4 tracks video engagement to understand content performance.",
      example: "User watches 50% of video → GA4 logs video_progress",
    },
    {
      title: "5. Ecommerce Tracking",
      event: "view_item / add_to_cart / purchase",
      explanation:
        "GA4 Ecommerce events help measure user shopping behavior.",
      example: "User adds shoes to cart → GA4 logs add_to_cart",
    },
    {
      title: "6. Form Submission",
      event: "generate_lead",
      explanation:
        "Useful for lead generation and contact form analysis.",
      example: "User submits inquiry form → GA4 logs generate_lead",
    },
    {
      title: "7. User Engagement",
      event: "user_engagement",
      explanation:
        "Measures active time spent on website or app.",
      example: "User stays active for 20 seconds → engagement tracked",
    },
    {
      title: "8. Traffic Source Analysis",
      event: "session_start",
      explanation:
        "GA4 helps identify whether users came from Google Ads, SEO, social media, or referrals.",
      example: "User arrives from Instagram → source tracked as social",
    },
  ];

  const products = [
    {
      name: "Running Shoes",
      price: "₹2,999",
      category: "Footwear",
    },
    {
      name: "Wireless Headphones",
      price: "₹1,999",
      category: "Electronics",
    },
    {
      name: "Smart Watch",
      price: "₹4,499",
      category: "Wearables",
    },
  ];

  const handleEvent = (eventName) => {
    alert(`GA4 Event Triggered: ${eventName}`);

    // Example GA4 Code
    console.log(`gtag('event', '${eventName}')`);
  };

  return (
    <div className="min-h-screen bg-slate-100 text-slate-900 p-6">
      <div className="max-w-7xl mx-auto space-y-8">
        <div className="bg-white rounded-3xl shadow-xl p-8 border">
          <h1 className="text-5xl font-bold mb-4">
            GA4 Learning Demo Website
          </h1>

          <p className="text-lg text-slate-700 leading-relaxed">
            This demo website is designed to help you learn Google Analytics 4
            practically. Every section demonstrates a real-world GA4 tracking
            concept used by companies in Ecommerce, Marketing Analytics, SaaS,
            and Product Analytics.
          </p>

          <div className="mt-6 grid md:grid-cols-4 gap-4">
            <div className="bg-blue-50 rounded-2xl p-4">
              <h3 className="font-semibold text-lg">Realtime Reports</h3>
              <p className="text-sm mt-2 text-slate-600">
                See live events instantly.
              </p>
            </div>

            <div className="bg-green-50 rounded-2xl p-4">
              <h3 className="font-semibold text-lg">Custom Events</h3>
              <p className="text-sm mt-2 text-slate-600">
                Track user interactions.
              </p>
            </div>

            <div className="bg-yellow-50 rounded-2xl p-4">
              <h3 className="font-semibold text-lg">Conversions</h3>
              <p className="text-sm mt-2 text-slate-600">
                Measure business goals.
              </p>
            </div>

            <div className="bg-purple-50 rounded-2xl p-4">
              <h3 className="font-semibold text-lg">Audience Analysis</h3>
              <p className="text-sm mt-2 text-slate-600">
                Understand visitor behavior.
              </p>
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          {sections.map((section, index) => (
            <div
              key={index}
              className="bg-white rounded-3xl shadow-lg p-6 border"
            >
              <h2 className="text-2xl font-bold mb-3">{section.title}</h2>

              <div className="mb-3 inline-block bg-slate-900 text-white px-3 py-1 rounded-full text-sm">
                Event Name: {section.event}
              </div>

              <p className="text-slate-700 leading-relaxed">
                {section.explanation}
              </p>

              <div className="mt-4 bg-slate-100 rounded-2xl p-4 text-sm">
                <span className="font-semibold">Example:</span>{" "}
                {section.example}
              </div>

              <button
                onClick={() => handleEvent(section.event)}
                className="mt-5 bg-slate-900 text-white px-5 py-3 rounded-2xl hover:scale-105 transition"
              >
                Trigger {section.event}
              </button>
            </div>
          ))}
        </div>

        <div className="bg-white rounded-3xl shadow-xl p-8 border">
          <h2 className="text-4xl font-bold mb-6">
            Ecommerce Tracking Demo
          </h2>

          <div className="grid md:grid-cols-3 gap-6">
            {products.map((product, index) => (
              <div
                key={index}
                className="border rounded-3xl p-5 hover:shadow-xl transition bg-slate-50"
              >
                <div className="h-48 rounded-2xl bg-slate-200 flex items-center justify-center text-xl font-semibold">
                  {product.name}
                </div>

                <div className="mt-4 space-y-2">
                  <h3 className="text-xl font-bold">{product.name}</h3>

                  <p className="text-slate-600">
                    Category: {product.category}
                  </p>

                  <p className="text-2xl font-bold">{product.price}</p>
                </div>

                <div className="mt-5 flex gap-3 flex-wrap">
                  <button
                   
  onClick={() => {

    window.dataLayer = window.dataLayer || [];

    window.dataLayer.push({
      event: "view_item",

      ecommerce: {
        currency: "INR",

        value: Number(
          product.price.replace('₹', '').replace(',', '')
        ),

        items: [
          {
            item_name: product.name,

            item_category: product.category,

            price: Number(
              product.price.replace('₹', '').replace(',', '')
            ),

            quantity: 1
          }
        ]
      }
    });

    alert(`Viewed ${product.name}`);
  }}
  className="bg-blue-600 text-white px-4 py-2 rounded-xl"
>
  View Item

                  </button>

                  <button
                    onClick={() => handleEvent('add_to_cart')}
                    className="bg-green-600 text-white px-4 py-2 rounded-xl"
                  >
                    Add to Cart
                  </button>

                  <button
                  
  onClick={() => {

    window.dataLayer = window.dataLayer || [];

    window.dataLayer.push({
      event: "purchase",

      ecommerce: {
        transaction_id: "T" + Date.now(),

        value: Number(
          product.price.replace('₹', '').replace(',', '')
        ),

        currency: "INR",

        items: [
          {
            item_name: product.name,
            item_category: product.category,

            price: Number(
              product.price.replace('₹', '').replace(',', '')
            ),

            quantity: 1
          }
        ]
      }
    });

    alert(`Purchase tracked for ${product.name}`);
  }}
  className="bg-purple-600 text-white px-4 py-2 rounded-xl"
>
  Purchase
</button>
                  
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-3xl shadow-xl p-8 border">
          <h2 className="text-4xl font-bold mb-6">
            Lead Generation Form
          </h2>

          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <input
                type="text"
                placeholder="Enter Name"
                className="w-full border rounded-2xl p-4"
              />

              <input
                type="email"
                placeholder="Enter Email"
                className="w-full border rounded-2xl p-4"
              />

              <textarea
                placeholder="Your Message"
                className="w-full border rounded-2xl p-4 h-32"
              />

              <button
                onClick={() => handleEvent('generate_lead')}
                className="bg-slate-900 text-white px-6 py-3 rounded-2xl"
              >
                Submit Lead Form
              </button>
            </div>

            <div className="bg-slate-100 rounded-3xl p-6">
              <h3 className="text-2xl font-bold mb-4">
                What GA4 Tracks Here?
              </h3>

              <ul className="space-y-3 text-slate-700 list-disc pl-5">
                <li>Form Starts</li>
                <li>Form Abandonment</li>
                <li>Successful Lead Submission</li>
                <li>Conversion Rate</li>
                <li>Traffic Source of Leads</li>
                <li>Device Type</li>
                <li>User Journey Before Conversion</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="bg-black text-white rounded-3xl p-8 shadow-xl">
          <h2 className="text-4xl font-bold mb-5">
            Real GA4 Integration Example
          </h2>

          <div className="bg-slate-900 rounded-2xl p-5 overflow-auto text-sm">
            <pre>
{`<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXXXX');

  gtag('event', 'add_to_cart', {
    currency: 'INR',
    value: 2999,
    item_name: 'Running Shoes'
  });
</script>`}
            </pre>
          </div>

          <div className="mt-6 text-slate-300 leading-relaxed">
            Replace <span className="font-bold">G-XXXXXXXXXX</span> with your
            GA4 Measurement ID after creating a property in Google Analytics.
          </div>
        </div>

        <div className="bg-gradient-to-r from-slate-900 to-slate-700 text-white rounded-3xl p-8 shadow-2xl">
          <h2 className="text-4xl font-bold mb-4">
            Suggested Learning Path
          </h2>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5 mt-6">
            <div className="bg-white/10 rounded-2xl p-5 backdrop-blur-sm">
              <h3 className="font-bold text-xl mb-2">Step 1</h3>
              <p>Learn Events & Parameters</p>
            </div>

            <div className="bg-white/10 rounded-2xl p-5 backdrop-blur-sm">
              <h3 className="font-bold text-xl mb-2">Step 2</h3>
              <p>Explore Realtime Reports</p>
            </div>

            <div className="bg-white/10 rounded-2xl p-5 backdrop-blur-sm">
              <h3 className="font-bold text-xl mb-2">Step 3</h3>
              <p>Build Funnels & Audiences</p>
            </div>

            <div className="bg-white/10 rounded-2xl p-5 backdrop-blur-sm">
              <h3 className="font-bold text-xl mb-2">Step 4</h3>
              <p>Connect GA4 with BigQuery & Looker Studio</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
